[workspace]
members = [
    "inox-core",
    "inox-gtk"
#    "inox-tui"
]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

# [patch.crates-io]
# notmuch-rs = { path="../notmuch-rs" }
